### ISSUE TITLE
Doesn't work on v0.17.0

### ISSUE THREAD

**Issue by EvD92** [IswPolymerElements/isw-footer-button-area#1]
I'm unable to use the bower install, gives multiple warnings.
Tried to download copy from GitHub, didn't work either :/

Polymer version
0.17.0

**Comment by rene-lindner-isw** [comment]
Sry for the late reply, didn't get an email notification. Polymer version 0.17.0 - is this the cli?

The Element is for Polymer 2.0, it uses the ES6 class syntax.

**Comment by rene-lindner-isw** [comment]
The install command from webcomponents.org works for me `bower install --save IswPolymerElements/isw-footer-button-area`, can you copy paste the warnings here?

**Comment by EvD92** [comment]
bower polymer#^1.0.0                   resolved https://github.com/polymer/polymer.git#1.9.1
bower polymer#^1.3.1                   resolved https://github.com/polymer/polymer.git#1.9.1
bower webcomponentsjs#^v1.0.0-rc.5      extract archive.tar.gz
bower webcomponentsjs#^v1.0.0-rc.5     resolved https://github.com/Polymer/webcomponentsjs.git#1.0.0-rc.11

Unable to find a suitable version for polymer, please choose one by typing one of the numbers below:
    1) polymer#^1.4.0 which resolved to 1.8.1 and is required by polymer-app
    2) polymer#^1.2.4 which resolved to 1.9.1 and is required by iron-menu-behavior#1.2.0
    3) polymer#^1.2.1 which resolved to 1.9.1 and is required by paper-behaviors#1.0.12
    4) polymer#^1.5.0 which resolved to 1.9.1 and is required by iron-collapse#1.3.0
    5) polymer#^1.2.0 which resolved to 1.9.1 and is required by iron-selector#1.5.2
    6) polymer#^1.1.0 which resolved to 1.9.1 and is required by iron-pages#1.0.8
    7) polymer#^1.6.0 which resolved to 1.9.1 and is required by app-layout#1.0.0
    8) polymer#^1.0.0 which resolved to 1.9.1 and is required by iron-iconset-svg#1.1.0
    9) polymer#^1.3.1 which resolved to 1.9.1 and is required by app-route#0.9.3
    10) polymer#^2.0.0-rc.2 which resolved to 2.0.0-rc.7 and is required by isw-footer-button-area#1.0.2

Prefix the choice with ! to persist it to bower.json

**Comment by rene-lindner-isw** [comment]
You're running on polymer 1.0, the element is for 2.0 (not hybrid). 

If you want to use it with 1.0 you have to create a fork and exchange the class declaration `class IswFooterButtonArea extends Polymer.Element` with the old 1.0 syntax `Polymer({ is: "element-name", ... });`

Or you just build it yourself, it's basically just a grey line ;)
